apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Release.Name }}-cluster
spec:
  kafka:
    replicas: {{ .Values.kafka.replicaCount }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: nodeport
        tls: false
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.kafka.disksize }}
        deleteClaim: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  zookeeper:
    replicas: {{ .Values.zookeeper.replicaCount }}
    storage:
      type: persistent-claim
      size: {{ .Values.zookeeper.disksize }}
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
